migrations launch added

diff --git a/hw12_13_14_15_16_calendar/deployments/docker-compose.yaml b/hw12_13_14_15_16_calendar/deployments/docker-compose.yaml
--- a/hw12_13_14_15_16_calendar/deployments/docker-compose.yaml
+++ b/hw12_13_14_15_16_calendar/deployments/docker-compose.yaml
@@ -10,7 +10,59 @@ services:
       - "${POSTGRES_HOST_PORT}:${POSTGRES_SERVICE_PORT}"
     volumes:
       - postgres_data:/var/lib/postgresql/data
+    healthcheck:
+      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
+      interval: 5s
+      timeout: 5s
+      retries: 5
     restart: unless-stopped
+  
+  migrations:
+    image: golang:1.24-alpine
+    container_name: migrations
+    environment:
+      HOST: database
+      PORT: ${POSTGRES_SERVICE_PORT}
+      USER: ${POSTGRES_USER}
+      PASSWORD: ${POSTGRES_PASSWORD}
+      DATABASE: ${POSTGRES_DB}
+    volumes:
+      - ../migrations:/migrations
+      - migration_status:/status
+    command: [
+      "sh", "-c",
+      "echo 'Installing goose...' && \
+      go install github.com/pressly/goose/v3/cmd/goose@v3.24.3 && \
+      echo 'Applying migrations...' && \
+      if goose -dir /migrations postgres \"host=$$HOST port=$$PORT user=$$USER password=$$PASSWORD dbname=$$DATABASE sslmode=disable\" up; then \
+        echo 'Migrations completed successfully' && \
+        touch /status/complete && \
+        echo 'Migration flag created'; \
+      else \
+        echo 'Migrations failed!' && \
+        exit 1; \
+      fi"
+    ]
+    depends_on:
+      database:
+        condition: service_healthy
+    restart: no
+
+  migration-wait:
+    image: alpine:latest
+    container_name: migration-wait
+    volumes:
+      - migration_status:/status
+    command: [
+      "sh", "-c",
+      "while [ ! -f /status/complete ];
+        do
+          echo 'Waiting for migrations to complete...';
+          sleep 1;
+        done;
+        echo 'Migrations ready!'"
+      ]
+    restart: no
 
   rabbitmq:
     image: rabbitmq:4.1.2-management-alpine
@@ -23,6 +75,12 @@ services:
       - "${RABBITMQ_UI_HOST_PORT}:${RABBITMQ_UI_SERVICE_PORT}"
     volumes:
       - rabbitmq_data:/var/lib/rabbitmq
+    healthcheck:
+      test: ["CMD", "rabbitmq-diagnostics", "ping"]
+      interval: 30s
+      timeout: 10s
+      retries: 5
+      start_period: 40s
     restart: unless-stopped
 
   calendar:
@@ -38,7 +96,8 @@ services:
     ports:
       - "${CALENDAR_HTTP_HOST_PORT}:${CALENDAR_HTTP_SERVICE_PORT}"
     depends_on:
-      - database
+      migration-wait:
+        condition: service_completed_successfully
     restart: unless-stopped
 
   scheduler:
@@ -53,8 +112,10 @@ services:
       CALENDAR_RMQ_USER: ${RABBITMQ_USER}
       CALENDAR_RMQ_PASSWORD: ${RABBITMQ_PASSWORD}
     depends_on:
-      - database
-      - rabbitmq
+      migration-wait:
+        condition: service_completed_successfully
+      rabbitmq:
+        condition: service_healthy
     restart: unless-stopped
 
   sender:
@@ -69,9 +130,11 @@ services:
       CALENDAR_RMQ_USER: ${RABBITMQ_USER}
       CALENDAR_RMQ_PASSWORD: ${RABBITMQ_PASSWORD}
     depends_on: 
-      - rabbitmq
+      rabbitmq:
+        condition: service_healthy
     restart: unless-stopped
       
 volumes:
   postgres_data:
   rabbitmq_data:
+  migration_status:
