production build is now applying migrations only on the clean start

diff --git a/hw12_13_14_15_16_calendar/deployments/docker-compose.yaml b/hw12_13_14_15_16_calendar/deployments/docker-compose.yaml
--- a/hw12_13_14_15_16_calendar/deployments/docker-compose.yaml
+++ b/hw12_13_14_15_16_calendar/deployments/docker-compose.yaml
@@ -31,16 +31,20 @@ services:
       - migration_status:/status
     command: [
       "sh", "-c",
-      "echo 'Installing goose...' && \
-      go install github.com/pressly/goose/v3/cmd/goose@v3.24.3 && \
-      echo 'Applying migrations...' && \
-      if goose -dir /migrations postgres \"host=$$HOST port=$$PORT user=$$USER password=$$PASSWORD dbname=$$DATABASE sslmode=disable\" up; then \
-        echo 'Migrations completed successfully' && \
-        touch /status/complete && \
-        echo 'Migration flag created'; \
+      "if [ ! -f /status-test/complete ]; then \
+        echo 'Installing goose...' && \
+        go install github.com/pressly/goose/v3/cmd/goose@v3.24.3 && \
+        echo 'Applying migrations...' && \
+        if goose -dir /migrations postgres \"host=$$HOST port=$$PORT user=$$USER password=$$PASSWORD dbname=$$DATABASE sslmode=disable\" up; then \
+          echo 'Migrations completed successfully' && \
+          touch /status/complete && \
+          echo 'Migration flag created'; \
+        else \
+          echo 'Migrations failed!' && \
+          exit 1; \
+        fi \
       else \
-        echo 'Migrations failed!' && \
-        exit 1; \
+        echo 'Migrations already applied'; \
       fi"
     ]
     depends_on:
